apiVersion: v2
name: cloudflared-gateway
description: Kubernetes Gateway API controller for Cloudflare Tunnels
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.28.0-0"
home: https://github.com/mccormickt/cloudflared-gateway
sources:
  - https://github.com/mccormickt/cloudflared-gateway
keywords:
  - cloudflare
  - tunnel
  - gateway-api
  - kubernetes
maintainers:
  - name: Tommy McCormick
    email: mccormickt9@gmail.com
