// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mccormickt/cloudflare-tunnel-controller/internal/cloudflare (interfaces: APIClient)
//
// Generated by this command:
//
//	mockgen -destination mock_cloudflare_test.go -package cloudflare_test github.com/mccormickt/cloudflare-tunnel-controller/internal/cloudflare APIClient
//

// Package cloudflare_test is a generated GoMock package.
package cloudflare_test

import (
	context "context"
	reflect "reflect"

	cloudflare "github.com/cloudflare/cloudflare-go"
	gomock "go.uber.org/mock/gomock"
)

// MockAPIClient is a mock of APIClient interface.
type MockAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockAPIClientMockRecorder
}

// MockAPIClientMockRecorder is the mock recorder for MockAPIClient.
type MockAPIClientMockRecorder struct {
	mock *MockAPIClient
}

// NewMockAPIClient creates a new mock instance.
func NewMockAPIClient(ctrl *gomock.Controller) *MockAPIClient {
	mock := &MockAPIClient{ctrl: ctrl}
	mock.recorder = &MockAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIClient) EXPECT() *MockAPIClientMockRecorder {
	return m.recorder
}

// CreateTunnel mocks base method.
func (m *MockAPIClient) CreateTunnel(arg0 context.Context, arg1 string) (cloudflare.Tunnel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTunnel", arg0, arg1)
	ret0, _ := ret[0].(cloudflare.Tunnel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTunnel indicates an expected call of CreateTunnel.
func (mr *MockAPIClientMockRecorder) CreateTunnel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTunnel", reflect.TypeOf((*MockAPIClient)(nil).CreateTunnel), arg0, arg1)
}

// DeleteTunnel mocks base method.
func (m *MockAPIClient) DeleteTunnel(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTunnel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTunnel indicates an expected call of DeleteTunnel.
func (mr *MockAPIClientMockRecorder) DeleteTunnel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTunnel", reflect.TypeOf((*MockAPIClient)(nil).DeleteTunnel), arg0, arg1)
}

// GetTunnel mocks base method.
func (m *MockAPIClient) GetTunnel(arg0 context.Context, arg1 string) (cloudflare.Tunnel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTunnel", arg0, arg1)
	ret0, _ := ret[0].(cloudflare.Tunnel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTunnel indicates an expected call of GetTunnel.
func (mr *MockAPIClientMockRecorder) GetTunnel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTunnel", reflect.TypeOf((*MockAPIClient)(nil).GetTunnel), arg0, arg1)
}

// ListTunnels mocks base method.
func (m *MockAPIClient) ListTunnels(arg0 context.Context) ([]cloudflare.Tunnel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTunnels", arg0)
	ret0, _ := ret[0].([]cloudflare.Tunnel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTunnels indicates an expected call of ListTunnels.
func (mr *MockAPIClientMockRecorder) ListTunnels(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTunnels", reflect.TypeOf((*MockAPIClient)(nil).ListTunnels), arg0)
}

// UpdateTunnel mocks base method.
func (m *MockAPIClient) UpdateTunnel(arg0 context.Context, arg1 cloudflare.TunnelUpdateParams) (cloudflare.Tunnel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTunnel", arg0, arg1)
	ret0, _ := ret[0].(cloudflare.Tunnel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTunnel indicates an expected call of UpdateTunnel.
func (mr *MockAPIClientMockRecorder) UpdateTunnel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTunnel", reflect.TypeOf((*MockAPIClient)(nil).UpdateTunnel), arg0, arg1)
}
