{{- if and (not .Values.cloudflare.existingSecret) (or .Values.cloudflare.accountId .Values.cloudflare.apiToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared-gateway.fullname" . }}-cloudflare
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  account-id: {{ .Values.cloudflare.accountId | quote }}
  api-token: {{ .Values.cloudflare.apiToken | quote }}
{{- end }}
