//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccessPolicy) DeepCopyInto(out *CloudflareAccessPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccessPolicy.
func (in *CloudflareAccessPolicy) DeepCopy() *CloudflareAccessPolicy {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareAccessPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccessPolicyList) DeepCopyInto(out *CloudflareAccessPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareAccessPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccessPolicyList.
func (in *CloudflareAccessPolicyList) DeepCopy() *CloudflareAccessPolicyList {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccessPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareAccessPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareAccessPolicySpec) DeepCopyInto(out *CloudflareAccessPolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]v1.LocalPolicyTargetReference, len(*in))
		copy(*out, *in)
	}
	if in.AudTag != nil {
		in, out := &in.AudTag, &out.AudTag
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareAccessPolicySpec.
func (in *CloudflareAccessPolicySpec) DeepCopy() *CloudflareAccessPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareAccessPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareOriginPolicy) DeepCopyInto(out *CloudflareOriginPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareOriginPolicy.
func (in *CloudflareOriginPolicy) DeepCopy() *CloudflareOriginPolicy {
	if in == nil {
		return nil
	}
	out := new(CloudflareOriginPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareOriginPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareOriginPolicyList) DeepCopyInto(out *CloudflareOriginPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareOriginPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareOriginPolicyList.
func (in *CloudflareOriginPolicyList) DeepCopy() *CloudflareOriginPolicyList {
	if in == nil {
		return nil
	}
	out := new(CloudflareOriginPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareOriginPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareOriginPolicySpec) DeepCopyInto(out *CloudflareOriginPolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]v1.LocalPolicyTargetReference, len(*in))
		copy(*out, *in)
	}
	if in.ProxyType != nil {
		in, out := &in.ProxyType, &out.ProxyType
		*out = new(string)
		**out = **in
	}
	if in.DisableChunkedEncoding != nil {
		in, out := &in.DisableChunkedEncoding, &out.DisableChunkedEncoding
		*out = new(bool)
		**out = **in
	}
	if in.KeepAliveConnections != nil {
		in, out := &in.KeepAliveConnections, &out.KeepAliveConnections
		*out = new(int32)
		**out = **in
	}
	if in.KeepAliveTimeout != nil {
		in, out := &in.KeepAliveTimeout, &out.KeepAliveTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.NoHappyEyeballs != nil {
		in, out := &in.NoHappyEyeballs, &out.NoHappyEyeballs
		*out = new(bool)
		**out = **in
	}
	if in.TLSTimeout != nil {
		in, out := &in.TLSTimeout, &out.TLSTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.TCPKeepAlive != nil {
		in, out := &in.TCPKeepAlive, &out.TCPKeepAlive
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.HTTP2Origin != nil {
		in, out := &in.HTTP2Origin, &out.HTTP2Origin
		*out = new(bool)
		**out = **in
	}
	if in.MatchSNIToHost != nil {
		in, out := &in.MatchSNIToHost, &out.MatchSNIToHost
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareOriginPolicySpec.
func (in *CloudflareOriginPolicySpec) DeepCopy() *CloudflareOriginPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareOriginPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelConfig) DeepCopyInto(out *CloudflareTunnelConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelConfig.
func (in *CloudflareTunnelConfig) DeepCopy() *CloudflareTunnelConfig {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnelConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelConfigList) DeepCopyInto(out *CloudflareTunnelConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudflareTunnelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelConfigList.
func (in *CloudflareTunnelConfigList) DeepCopy() *CloudflareTunnelConfigList {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudflareTunnelConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelConfigSpec) DeepCopyInto(out *CloudflareTunnelConfigSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.MetricsPort != nil {
		in, out := &in.MetricsPort, &out.MetricsPort
		*out = new(int32)
		**out = **in
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelConfigSpec.
func (in *CloudflareTunnelConfigSpec) DeepCopy() *CloudflareTunnelConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudflareTunnelConfigStatus) DeepCopyInto(out *CloudflareTunnelConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudflareTunnelConfigStatus.
func (in *CloudflareTunnelConfigStatus) DeepCopy() *CloudflareTunnelConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CloudflareTunnelConfigStatus)
	in.DeepCopyInto(out)
	return out
}
